schedule_optimizer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scheduler.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scheduler/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
   
    path('', views.Login_view, name='Login_view'),
    path('manage-users/', views.manage_users, name='manage_users'),
    path('add-user/', views.add_user, name='add_user'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('home/', views.home, name='home'),
    path('manage_colleges/', views.manage_colleges, name='manage_colleges'),
    path('edit_college/<int:college_id>/', views.edit_college, name='edit_college'),
    path('add_lecturer/', views.add_lecturer, name='add_lecturer'),
    path('delete-lecturer/<int:lecturer_id>/', views.delete_lecturer, name='delete_lecturer'),
    path('add_department/', views.add_department, name='add_department'),
    path('delete-department/<int:department_id>/', views.delete_department, name='delete_department'),
    path('add_room/', views.add_room, name='add_room'),
    path('choose/', views.choose, name='choose'),
    path('delete-room/<int:room_id>/', views.delete_room, name='delete_room'),
    path('add_course/', views.add_course, name='add_course'),
    path('edit-course/<int:course_id>/', views.edit_course, name='edit_course'),
    path('delete-course/<int:course_id>/', views.delete_course, name='delete_course'),
    path('term/', views.term, name='term'),
    path('generate_schedule/', views.generate_schedule, name='generate_schedule'),
    path('generate_schedule_final/', views.generate_schedule_final, name='generate_schedule_final'),
    path("export_schedule/", views.export_schedule_to_excel, name="export_schedule_to_excel"),
    path('export_schedule_to_pdf/', views.export_schedule_to_pdf, name='export_schedule_to_pdf'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scheduler/models.py
from django.db import models
from django.contrib.auth.models import User



class College(models.Model):
    name = models.CharField(max_length=100)
    user = models.OneToOneField(User, models.SET_NULL ,null=True, blank=True)  # لكل كلية حساب مرتبط
    logo = models.ImageField(upload_to='college_logos/', null=True, blank=True)  # حقل الشعار
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Semester(models.Model):
    semester_name = models.CharField(max_length=30, null=True)
    semester_number = models.IntegerField()
    college = models.ForeignKey(College, on_delete=models.CASCADE)
    

    def __str__(self):
        return str(self.semester_name)  
    
class Department(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=20)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE, null=True)
    college = models.ForeignKey(College, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.name}-{self.semester}"

class Lecturer(models.Model):
    name = models.CharField(max_length=100)
    number = models.IntegerField()
    college = models.ForeignKey(College, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Room(models.Model):
    ROOM_TYPES = [
        ('hall', 'قاعة'),
        ('computer_lab', 'معمل حاسوب'),
        ('chemistry_lab', 'معمل كيمياء'),
        ('rocks_lab', 'معمل صخور'),
        ('biology_lab', 'معمل أحياء'),
        ('movable_prosthetics_lab', 'معمل التركيبات المتحركة'),
        ('dental_lab', 'معمل صناعة الأسنان'),
        ('fixed_prosthetics_lab', 'معمل التركيبات الثابتة'),
        ('casting_lab', 'معمل الصب'),
        ('conservative_lab', 'معمل العلاج التحفظي'),
        ('electrical_engineering_lab', 'معمل هندسة كهربائية وإلكترونية'),
        ('materials_engineering_lab', 'معمل هندسة المواد'),
        ('renewable_energy_lab', 'معمل الطاقات المتجددة'),
    ]
    name = models.CharField(max_length=50)
    capacity = models.IntegerField()
    college = models.ForeignKey(College, on_delete=models.CASCADE)
    room_type = models.CharField(max_length=400, choices=ROOM_TYPES, default='hall')
    def __str__(self):
        return f"{self.name} - {self.get_room_type_display()}"
    
    
class Course(models.Model):
    ROOM_TYPES = [
        ('hall', 'قاعة'),
        ('computer_lab', 'معمل حاسوب'),
        ('chemistry_lab', 'معمل كيمياء'),
        ('rocks_lab', 'معمل صخور'),
        ('biology_lab', 'معمل أحياء'),
    ]
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=20)
    department = models.ManyToManyField(Department)
    lecturer = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    student_count = models.IntegerField(default=0)
    college = models.ForeignKey(College, on_delete=models.CASCADE)
    required_room_type = models.CharField(max_length=20, choices=ROOM_TYPES, default='hall')

    def __str__(self):
        return self.name




class Term(models.Model):
    name = models.CharField(max_length=50)  
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name



class Days(models.Model):
    name = models.CharField(max_length=50) 
    
    def __str__(self):
        return self.name
    
    
class Periods(models.Model):
    name = models.CharField(max_length=50) 
    
    def __str__(self):
        return self.name
    
class ScheduleSettings(models.Model):
    college = models.ForeignKey(College, on_delete=models.CASCADE)  # المستخدم المرتبط بالإعدادات
    days = models.ManyToManyField(Days)  # الأيام المختارة
    periods = models.ManyToManyField(Periods)  # الفترات المختارة
     
    def __str__(self):
        return f"Settings for {self.college.name}"
 

templates/add_course.html
{% extends 'base.html'%}
{% load static %}

{% block contant %}
<div class="add">
    <nav class="navbar sticky-top"  >
        <div class="container-fluid">
          <i class="bi bi-calendar-event fs-2 text-light"></i>  <!-- أيقونة الجدول الدراسي -->   
          <h2 class="text-light"> الجدول الدراسي الذكي</h2>
          <button class="navbar-toggler " type="button"  data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon "></span>
          </button>
          <n class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header " >
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">القائمة الرئسية </h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'home' %}">الصفحة الرئسية </a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'add_lecturer' %}">اضافة محاضر </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'add_department' %}">اضافة قسم دراسي</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'add_room' %}">اضافة قاعة دراسية</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'add_course' %}">اضافة مقرر دراسي </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'generate_schedule' %}">توليد الجدول </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'generate_schedule_final' %}">توليد جدول الامتحانات </a>
                  </li>
              </ul>
            
        </div>
    </nav>
    <div class="container mt-5 add" dir="rtl">
        <h2>إضافة مقرر دراسي</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label class="fw-bold" for="name">اسم المقرر:</label>
                <input type="text" name="name" id="name" class="form-control" required>
            </div>
            <div class="form-group">
                <label class="fw-bold" for="code">رمز المقرر:</label>
                <input type="text" name="code" id="code" class="form-control" required>
            </div>
            <div class="form-group">
                <label class="fw-bold" for="required_room_type">نوع الغرفة المطلوبة:</label>
                <select name="required_room_type" id="required_room_type" class="form-control" required>
                    <option value="hall">قاعة</option>
                    <option value="computer_lab">معمل حاسوب</option>
                    <option value="chemistry_lab">معمل كيمياء</option>
                    <option value="rocks_lab">معمل صخور</option>
                    <option value="biology_lab">معمل أحياء</option>
                </select>
            </div>
            <div class="form-group bg-dark-subtle mt-2 p-3 w-25">
                <label class="fw-bold" for="departments">الأقسام المرتبطة:</label>
                <div id="departments">
                    {% for department in departments %}
                        <div class="form-check">
                            <input type="checkbox" name="departments" value="{{ department.id }}" class="form-check-input" id="department_{{ department.id }}">
                            <label class="fw-bold form-check-label" for="department_{{ department.id }}">{{ department }}</label>
                        </div>
                    {% endfor %}
                </div>
            </div>
            
            <div class="form-group">
                <label  for="lecturer" class="fw-bold">المحاضر:</label>
                <select name="lecturer" id="lecturer" class="form-control">
                    {% for lecturer in lecturers %}
                        <option value="{{ lecturer.id }}">{{ lecturer.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label class="fw-bold" for="student_count">عدد الطلاب:</label>
                <input type="number" name="student_count" id="student_count" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-primary mt-3">إضافة مقرر دراسي</button>
        </form>

        <h2 class="mt-5">قائمة المقررات</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>اسم المقرر</th>
            <th>رمز المقرر</th>
            <th>نوع الغرفة المطلوبة</th>
            <th>القسم</th>
            <th>المحاضر</th>
            <th>عدد الطلاب</th>
            <th>الإجراءات</th>
        </tr>
    </thead>
    <tbody>
        {% for course in courses %}
        <tr>
            <td>{{ course.name }}</td>
            <td>{{ course.code }}</td>
            <td>{{ course.get_required_room_type_display }}</td>
            <td>
                {% for department in course.department.all %}
                    {{ department}} 
                {% endfor %}
            </td>
            <td>{{ course.lecturer.name }}</td>
            <td>{{ course.student_count }}</td>
            <td>
                <a href="{% url 'edit_course' course.id %}" class="btn btn-primary btn-sm my-2 w-100">تعديل</a>
                <a href="{% url 'delete_course' course.id %}" class="btn btn-danger btn-sm w-100">حذف</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
 
    </div>


</div>
{% endblock %}

templates/add_department.html
{% extends 'base.html'%}
{% load static %}

{% block contant %}
<div class="add">
  <nav class="navbar sticky-top"  >
    <div class="container-fluid">
      <i class="bi bi-calendar-event fs-2 text-light"></i>  <!-- أيقونة الجدول الدراسي -->   
      <h2 class="text-light"> الجدول الدراسي الذكي</h2>
      <button class="navbar-toggler " type="button"  data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon "></span>
      </button>
      <n class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header " >
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">القائمة الرئسية </h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">الصفحة الرئسية </a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'add_lecturer' %}">اضافة محاضر </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'add_department' %}">اضافة قسم دراسي</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'add_room' %}">اضافة قاعة دراسية</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'add_course' %}">اضافة مقرر دراسي </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'generate_schedule' %}">توليد الجدول </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'generate_schedule_final' %}">توليد جدول الامتحانات </a>
              </li>
          </ul>
        
    </div>
</nav>
  
<div class="container mt-5 add" dir="rtl">
    <h2>إضافة قسم</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">اسم القسم:</label>
            <input type="text" name="name" id="name" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="code">رمز القسم:</label>
            <input type="text" name="code" id="name" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="semester">الفصل الدراسي:</label>
          <select name="semester" id="semester" class="form-control">
              {% for semester in semesters %}
                  <option value="{{ semester.id }}">{{ semester.semester_name }}</option>
              {% endfor %}
          </select>
      </div>
        <button type="submit" class="btn btn-primary mt-3">إضافة قسم</button>
    </form>

    <h2 class="mt-5">قائمة الأقسام</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>اسم القسم</th>
                <th>رمز القسم</th>
                <th>الفصل الدراسي</th>
                <th>الحذف</th>
    
            </tr>
        </thead>
        <tbody>
            {% for department in departments %}
            <tr>
                <td>{{ department.name }}</td>
                <td>{{ department.code }}</td>
                <td>{{ department.semester.semester_name }}</td>
                <td>
                  <a href="{% url 'delete_department' department.id %}" class="btn btn-danger btn-sm">حذف</a>
              </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div></div>
{% endblock %}

templates/add_lecturer.html
{% extends 'base.html'%}
{% load static %}

{% block contant %}
<div class="add">
  <nav class="navbar sticky-top"  >
    <div class="container-fluid">
      <i class="bi bi-calendar-event fs-2 text-light"></i>  <!-- أيقونة الجدول الدراسي -->   
      <h2 class="text-light"> الجدول الدراسي الذكي</h2>
      <button class="navbar-toggler " type="button"  data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon "></span>
      </button>
      <n class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header " >
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">القائمة الرئسية </h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">الصفحة الرئسية </a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'add_lecturer' %}">اضافة محاضر </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'add_department' %}">اضافة قسم دراسي</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'add_room' %}">اضافة قاعة دراسية</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'add_course' %}">اضافة مقرر دراسي </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'generate_schedule' %}">توليد الجدول </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'generate_schedule_final' %}">توليد جدول الامتحانات </a>
              </li>
          </ul>
        
    </div>
</nav>
  
<div class="container mt-5 add" dir="rtl">
    <h2>إضافة محاضر</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">اسم المحاضر:</label>
            <input type="text" name="name" id="name" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="number">رقم المحاضر: </label>
            <input type="text" name="number" id="department" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary mt-3">إضافة المحاضر</button>
    </form>

    <h2 class="mt-5">قائمة المحاضرين</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>الاسم</th>
                <th>رقم المحاضر</th>
                <th>الحذف</th>
    
            </tr>
        </thead>
        <tbody>
          {% for lecturer in lecturers %}
            <tr>
                <td>{{ lecturer.name }}</td>
                <td>{{ lecturer.number }}</td>
                <td>
                  <a href="{% url 'delete_lecturer' lecturer.id %}" class="btn btn-danger btn-sm">حذف</a>
              </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div></div>
{% endblock %}

templates/add_room.html
{% extends 'base.html'%}
{% load static %}

{% block contant %}
<div class="add">
  <nav class="navbar sticky-top"  >
    <div class="container-fluid">
      <i class="bi bi-calendar-event fs-2 text-light"></i>  <!-- أيقونة الجدول الدراسي -->   
      <h2 class="text-light"> الجدول الدراسي الذكي</h2>
      <button class="navbar-toggler " type="button"  data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon "></span>
      </button>
      <n class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header " >
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">القائمة الرئسية </h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">الصفحة الرئسية </a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'add_lecturer' %}">اضافة محاضر </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'add_department' %}">اضافة قسم دراسي</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'add_room' %}">اضافة قاعة دراسية</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'add_course' %}">اضافة مقرر دراسي </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'generate_schedule' %}">توليد الجدول </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'generate_schedule_final' %}">توليد جدول الامتحانات </a>
              </li>
          </ul>
        
    </div>
</nav>
<div class="container mt-5 add" dir="rtl">
  <h2>إضافة غرفة دراسية</h2>
  <form method="POST">
      {% csrf_token %}
      <div class="form-group">
          <label for="name">اسم الغرفة الدراسية:</label>
          <input type="text" name="name" id="name" class="form-control" required>
      </div>
      <div class="form-group">
          <label for="capacity">سعة الغرفة الدراسية: </label>
          <input type="number" name="capacity" id="capacity" class="form-control" required>
      </div>
      <div class="form-group">
        <label for="room_type">نوع الغرفة:</label>
        <select name="room_type" id="room_type" class="form-control" required>
            <option value="hall">قاعة</option>
            <option value="computer_lab">معمل حاسوب</option>
            <option value="chemistry_lab">معمل كيمياء</option>
            <option value="rocks_lab">معمل صخور</option>
            <option value="biology_lab">معمل أحياء</option>
            <option value="movable_prosthetics_lab">معمل التركيبات المتحركة</option>
            <option value="dental_lab">معمل صناعة الأسنان</option>
            <option value="fixed_prosthetics_lab">معمل التركيبات الثابتة</option>
            <option value="casting_lab">معمل الصب</option>
            <option value="conservative_lab">معمل العلاج التحفظي</option>
            <option value="electrical_engineering_lab">معمل هندسة كهربائية وإلكترونية</option>
            <option value="materials_engineering_lab">معمل هندسة المواد</option>
            <option value="renewable_energy_lab">معمل الطاقات المتجددة</option>
        </select>
    </div>
    
      <button type="submit" class="btn btn-primary mt-3">إضافة غرفة دراسية</button>
  </form>

  <h2 class="mt-5">قائمة الغرف الدراسية</h2>
  <table class="table table-striped">
      <thead>
          <tr>
              <th>اسم القاعة</th>
              <th>سعة القاعة</th>
              <th>نوع الغرفة</th>
              <th>الحذف</th>
          </tr>
      </thead>
      <tbody>
          {% for room in rooms %}
          <tr>
              <td>{{ room.name }}</td>
              <td>{{ room.capacity }}</td>
              <td>{{ room.get_room_type_display }}</td>
              <td>
                <a href="{% url 'delete_room' room.id %}" class="btn btn-danger btn-sm">حذف</a>
              </td>
          </tr>
          {% endfor %}
      </tbody>
  </table>
</div>
</div>
{% endblock %}

templates/add_user.html
{% extends 'base.html' %}
{% load static %}

{% block contant %}
<div class="container mt-5" dir="rtl">
    <h1 class="text-center mb-4">إضافة مستخدم جديد</h1>
    
    <form method="post" class="form-container">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="username" class="form-label">اسم المستخدم</label>
            <input type="text" name="username" class="form-control" id="username" required>
        </div>

        <div class="mb-3">
            <label for="email" class="form-label">البريد الإلكتروني</label>
            <input type="email" name="email" class="form-control" id="email" required>
        </div>

        <div class="mb-3">
            <label for="password" class="form-label">كلمة المرور</label>
            <input type="password" name="password" class="form-control" id="password" required>
        </div>

        <div class="mb-3 form-check">
            <input type="checkbox" name="is_superuser" value="true" class="form-check-input" id="is_admin">
            <label class="form-check-label" for="is_admin">هل هو مشرف؟</label>
        </div>

        <div class="d-grid gap-2">
            <button type="submit" class="btn btn-primary">إضافة مستخدم</button>
        </div>
    </form>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <title>الجدول الدراسي </title>
    <link rel="icon" href="{% static 'img/icon_AI.png' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

    <style>
        body {
            margin: 0;
            padding: 0;
            background-image: url("{% static 'img/table_AI.jpg' %}"); /* ضع رابط الصورة هنا */
            background-size: cover; /* لجعل الصورة تغطي الشاشة بالكامل */
            background-repeat: no-repeat; /* لمنع تكرار الصورة */
            background-attachment: fixed; /* لجعل الخلفية ثابتة أثناء التمرير */
            background-position: center 16%; /* لوضع الصورة في المنتصف */
        }
        img{
            width:48px;
        }
    </style>
</head>
<body class="body h-100">
    {% block contant %}
    {% endblock %}

    <script src="{%static 'js/main.js'%}"></script>
    <script src="{%static 'js/bootstrap.bundle.min.js'%}"></script>
    <script>
        function confirmDelete(url) {
            if (confirm("هل أنت متأكد من أنك تريد حذف هذا المستخدم؟")) {
                window.location.href = url;  // إذا أكد، سيتم الانتقال إلى رابط الحذف
            }
        }
    </script>
</body>
</html>

templates/error.html
{% extends 'base.html' %}
{% load static %}

{% block contant %}
<div class="container my-5">
    <div class="text-danger" dir="rtl">
        <h1 class="error-title">خطأ</h1>
        <p class="error-message">{{ message }}</p>
        <a class="text-light" href="{% url 'home' %}">العودة إلى الصفحة الرئيسية</a>
    </div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html'%}
{% load static %}

{% block contant %}
<div class="log" >
    <div class="login-container">
        <form method="POST" class="login-form" dir="rtl">
            {% csrf_token %}
            <h2>تسجيل الدخول</h2>
             {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                </div>
             {% endif %}

            <input type="text" name="username" placeholder="اسم المستخدم" required>
            <input type="password" name="password" placeholder="كلمة المرور" required>
            <button type="submit">تسجيل الدخول</button>
        </form>
    </div>
</div>
  {% endblock %}